server {
    listen 80;
    client_max_body_size 10M; # Cho phép upload file tối đa 10MB 
    
    # 1. Chạy React App
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # Xử lý lỗi 404 khi F5 React Router
    }

    # 2. Map đường dẫn /uploads/ trực tiếp vào thư mục Mount
    location /uploads/ {
        root /usr/share/nginx/html; 
         autoindex off; 
         access_log off;
         expires 30d; 
     
        # Chỉ phục vụ các đuôi file an toàn 
        location ~* \.(jpg|jpeg|png|gif|webp)$ { 
          try_files $uri =404; 
        } 
        
        # Chặn các request khác vào thư mục này 
        location ~* /uploads/.* { 
           deny all; 
        } 
    }

    # 3. CHUYỂN TIẾP API (ĐÃ CẬP NHẬT THEO CONTEXT PATH)
    location /hotel/ { 
        # Đẩy request vào mạng nội bộ Docker tới service backend-api
        proxy_pass http://backend-api:8080/hotel/; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
